name: Rust - V1.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo
      run: sudo apt-get update; sudo apt-get install cargo -y -q
    - name: Build
      run:  git switch -c 8c09040cc235b9ae1a25d4d1d29a23bca1f6f862; sudo chmod 755 Install.sh; sudo ./Install.sh
    - name: Run
      run: sudo hts4 -a

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: git switch -c 8c09040cc235b9ae1a25d4d1d29a23bca1f6f862 ;cargo build --verbose
    - name: Run
      run: cargo run --verbose --release -- -a
      
  build-mac:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: git switch -c 8c09040cc235b9ae1a25d4d1d29a23bca1f6f862 ;cargo build --verbose
    - name: Run
      run: cargo run --verbose --release -- -a
  
